### ISSUE TITLE
Come up with True/False questionnaire 

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#29]

**Comment by machikoyasuda** [comment]
1. Have you made a static web page with HTML, CSS before and deployed it? T/F
2. Have you worked on an Rails app? T/F
3. Have you used Git on the Terminal and pushed or made a PR? T/F

We can then sort people into two-three groups:
1. First-Timers: learn how to make a static site on GitHub
2. App-makers: Want to focus on making their first/big app - want to focus on learning the framework
3. Adv: Have worked on apps in production - want to focus on testing, refactoring, beyond just learning the framework

**Comment by server-monitor** [comment]
Funny you should ask. I made a demo app for a presentation about
geo-location for my Ruby Meetup in my area. It's not a static site though
since it's a Rails 5 app. It is deployed to Heroku:

https://geo-locatr.herokuapp.com/

It's a simple app. You enter a host or domain name or IP address and the
app will tell you the street address. It will also show you the location on
the map using Google maps. The Google maps gem is pretty cool to play
around with.

It's not mobile friendy yet though. I was under the impression that
Bootstrap will automatically take care of that but I was mistaken. I'll
work on this later on.

Critiques, suggestions are welcome. I'll share the source with the group
once I cleaned it up. It's quite dirty right now because I was trying a few
things before I deployed it.
1. True and False
2. True (worked on Rails apss as personal projects, not work-related)
3. Pushed but not PR'd (personal projects)

**Comment by IanDCarroll** [comment]
Is this going to be distributed to people at the meetup?
When False, Should there be a thing to do to make it true?
Is this the best order to tackle basics if there are multiple falsenesses?

**Comment by machikoyasuda** [comment]
@ian yes and yes
its our opiniom, of course. its to help us make groups of similarly-leveled people so everyone can work towards their own goals. we will find projects to work on that are appropriate for each level group. 

```
    _____________________________
```

**Comment by IanDCarroll** [comment]
**That sounds delightful!** 
for me:
1. True (Could do more with CSS tho)
2. False
3. True

And another thing: Should we implement this after the standup? Here's a way I could see it work:
- **Break into 4 clusters:** 1F, 2F, 3F, and "Open-Source Bug Patrol"
- **We'd need 3 special someones** (Or 1 very brave soul) who has done it already to be so kind as to guide those groups (Or at least check up on them every half-hour or so to make sure they haven't devolved into eating each other). ( :cake: || :skull: )

**Question:** Once someone has 3T's, will they be ready for "OSBP"? Or are there more basic skills beyond Codecademy.com that such a hypothetical person would need before that?
