### ISSUE TITLE
Tuesday, July 5th 2016 - Scratch Pad + Summary

### ISSUE THREAD

**Issue by jendiamond** [fullstackla/pairing-meetup#43]

**Comment by hash167** [comment]
bundle exec rake test TEST=test/acceptance/team_test.rb

**Comment by server-monitor** [comment]
# Run one mini test...

ruby path/to/test/file_test.rb --name name_of_test_method_name

# Example...

ruby test/exercism/user_test.rb --name test_user_not_a_guest

ruby test/acceptance/team_test.rb --name test_managing_a_team_as_sole_manager

**Comment by jendiamond** [comment]
Kit says:The Mystery Guest

**Comment by kpearson** [comment]
[The mystery guest](http://xunitpatterns.com/Obscure%20Test.html#Mystery%20Guest) testing anti-pattern is where the test reader is not able to see the cause and effect between fixture and verification logic because part of it is done outside the Test Method.

An blog post that I think covers this well is [mystery-guest](https://robots.thoughtbot.com/mystery-guest) by [Dan Croak](https://twitter.com/croaky) for thoughtbot.
