### ISSUE TITLE
Video - Andrea Kao / Homebrew

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#76]
As a meetup member/fan, I would like to be able to watch Andrea Kao's talk on Homebrew/Outreachy.

**Comment by IanDCarroll** [comment]
Wow! All right, maybe the simplest way to do this would be to add a link under FullStackLA.

Or were you looking for embedded video, which might morph the scope of the project quite a bit.

**Comment by IanDCarroll** [comment]
This for the main website that @kpearson  is working on?

**Comment by machikoyasuda** [comment]
@IanDCarroll 

Steps:
1. Someone has to upload that video, edit it, make it viewable and hearable
2. Someone has to find a place to upload it: YouTube, Vimeo, etc.
3. Someone can also add that embed URL into a static HTML page.

It can go anywhere at this point, hypothetically.

**Comment by IanDCarroll** [comment]
Steps:
- [ ] Someone has to upload that video, edit it, make it viewable and hearable @kpearson, if you don't object, since you've got the camera.
- [ ] Someone has to find a place to upload it: YouTube, Vimeo, etc. - **Needs a person**
- [ ] Someone can also add that embed URL into a static HTML page. - **Needs a person**

**Comment by machikoyasuda** [comment]
I thus grant you  @IanDCarroll permission to close / rewrite / reword / add lists to / add emojis to any issue I put on here. I use https://github.com/hoodiehq/camp/issues/14 this kind of issue as a template.

**Comment by IanDCarroll** [comment]
Steps:
- [ ] Someone has to upload that video, edit it, make it viewable and hearable @kpearson, if you don't object, since you've got the camera.
- [ ] Someone has to find a place to upload it: YouTube, Vimeo, etc. - **Needs a person**
- [ ] Someone can also add that embed URL into a static HTML page. - **Needs a person**

**Comment by machikoyasuda** [comment]
What is the blocker on this? @kpearson

**Comment by kpearson** [comment]
Editing. :-/

— Kit

On Sat, Oct 29, 2016 at 10:45 PM Machiko Yasuda

<
mailto:Machiko Yasuda notifications@github.com

> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

What is the blocker on this?
https://github.com/kpearson

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/fullstackla/pairing-meetup/issues/76#issuecomment-257133507
, or

**Comment by machikoyasuda** [comment]
Can you send me a few stills for now? So we can have a placeholder for our "Video coming soon" page to send to Outreachy/Homebrew.

**Comment by machikoyasuda** [comment]
@kpearson What is the status on this?

1. What is our YouTube URL? (doesn't have to be a vanity URL)
2. Is the video up somewhere? I searched all sorts of words and nothing came up.

**Comment by machikoyasuda** [comment]
for now, we can link these 2:
https://speakerdeck.com/eirinikos/fullstack-2016-08-24-contributing-to-homebrew

https://eirinikos.github.io/2016/08/17/fullstack-q-a/

and we can have copy that says "Video to come."

**Comment by machikoyasuda** [comment]
Youtube Link for Andrea's is here https://www.youtube.com/watch?v=sMhodgiWyhk
