### ISSUE TITLE
How can we make removable semi-adhesive laptop nametags for our members?

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#98]
#### User Story

As a meetup attendee & enthusiast,
I want people to have some kind of permanent almost-sticker name tags for attendees,
so that I can more easily learn people's names.

I WANT TO PUT THE STICKER ON MY LAPTOP THO!!!

#### Current Behavior

I learn everyone's names at Stand Up, and then I immediately forget.

#### Your Environment

- in real life
#### Additional Context
- Since we don't have money really, the solution can/should be as cheap as possible for now :)
#### Credits
- Who wants to sponsor these? :) 

---

[Made at Fullstack LA](https://meetup.com/la-fullstack/events/234620974) :zap:

**Comment by machikoyasuda** [comment]
A white sticker with an area to write your name in marker: https://www.stickermule.com/products/transfer-stickers could be fun!

**Comment by machikoyasuda** [comment]
Name tag inspiration from @leighphan https://twitter.com/rachelnabors/status/785558069782642688

**Comment by xuhdev** [comment]
How about the simplest note sticker like last time we did?

**Comment by machikoyasuda** [comment]
@xuhdev Those were okay for one-time use... a more permanent one might be funner. :)

**Comment by machikoyasuda** [comment]
@xyzzyismagic ideas? 
we have $$ from Sticker Mule

**Comment by machikoyasuda** [comment]
@xyzzyismagic https://www.stickermule.com/

**Comment by machikoyasuda** [comment]
@xyzzyismagic Can you write me a list of materials I should give you to start a logo/branding client/designer conversation?

**Comment by xyzzyismagic** [comment]
@machikoyasuda 
- If you want a material that both sticks well and is easily removed from laptop surfaces, I recommend vinyl. This is probably the costliest solution.
- If you want something cost-effective, I'd look into getting a roll of [wall-pops](http://www.wallpops.com/white-dry-erase-decal.aspx), dry-erase sticker and cut it down for people to write on.
- If you want to use Sticker Mule since you have Sticker Mule $$, it looks like they offer a [sample pack](https://www.stickermule.com/products/sample-pack) for $1, so I'd get that and stick them on a a few laptoppy surfaces.
- API Equality-LA does the standard hello-my-name-is nametags, which works when everyone gets up to mingle too.

The materials I ask for a branding project is:
- The answer to "What situation made you decide you needed a brand for your organization?"
- Files of any past branding & why those no longer suit the purposes of the organization.
- Examples or description of branding/visuals you like in any way you're most comfortable communicating that.
- Important dates.
- Budget
- The answer to: "Who are you communicating to?"
- The answer to: "Where are you communicating this?"
- A phone call or meeting to clear up anything once I receive as many as those as possible via e-mail. :)
